name: NodeCholo.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./eventos-choclofront

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      working-directory: ${{ env.working-directory }}
    - run: npm ci
      working-directory: ${{ env.working-directory }}
    - run: npm run build --if-present
      working-directory: ${{ env.working-directory }}
    - run: npm test
      working-directory: ${{ env.working-directory }}
